# Form implementation generated from reading ui file 'D:\Junior (1st semester)\Machine Learning\ML_PyCharm\project_retail\ui\LoginMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(569, 397)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 20, 171, 251))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:\\Junior (1st semester)\\Machine Learning\\ML_PyCharm\\project_retail\\ui\\../images/ic_admin.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(210, 20, 331, 251))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 91, 31))
        self.label_2.setObjectName("label_2")
        self.lineEditUsername = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEditUsername.setGeometry(QtCore.QRect(20, 50, 271, 31))
        self.lineEditUsername.setObjectName("lineEditUsername")
        self.lineEditPassword = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEditPassword.setGeometry(QtCore.QRect(20, 130, 271, 31))
        self.lineEditPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEditPassword.setReadOnly(False)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(20, 100, 91, 31))
        self.label_4.setObjectName("label_4")
        self.checkBoxSave = QtWidgets.QCheckBox(parent=self.groupBox_2)
        self.checkBoxSave.setGeometry(QtCore.QRect(20, 180, 101, 21))
        self.checkBoxSave.setObjectName("checkBoxSave")
        self.pushButtonLogin = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.pushButtonLogin.setGeometry(QtCore.QRect(50, 210, 91, 31))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\Junior (1st semester)\\Machine Learning\\ML_PyCharm\\project_retail\\ui\\../images/ic_login.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonLogin.setIcon(icon)
        self.pushButtonLogin.setObjectName("pushButtonLogin")
        self.pushButtonExit = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.pushButtonExit.setGeometry(QtCore.QRect(160, 210, 91, 31))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("D:\\Junior (1st semester)\\Machine Learning\\ML_PyCharm\\project_retail\\ui\\../images/ic_exit.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonExit.setIcon(icon1)
        self.pushButtonExit.setObjectName("pushButtonExit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 569, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Login Infor:"))
        self.label_2.setText(_translate("MainWindow", "User Name:"))
        self.lineEditUsername.setText(_translate("MainWindow", "hoa@gmail.com"))
        self.lineEditPassword.setText(_translate("MainWindow", "4678"))
        self.label_4.setText(_translate("MainWindow", "Password:"))
        self.checkBoxSave.setText(_translate("MainWindow", "Save infor"))
        self.pushButtonLogin.setText(_translate("MainWindow", "Login"))
        self.pushButtonExit.setText(_translate("MainWindow", "Exit"))
